import { NextIntlClientProvider } from 'next-intl';
import { Albert_Sans } from "next/font/google";
import { getLocale } from 'next-intl/server';
import { ThemeProvider } from 'next-themes';
import localFont from 'next/font/local';
import type { Metadata } from "next";
import "@/app/globals.css";

import Sidebar from '@/components/layout/Sidebar';
import Navbar from '@/components/layout/Navbar';

const albertSans = Albert_Sans({
    variable: "--font-albert-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const myFont = localFont({
    src: '../../public/fonts/LufgaRegular.ttf',
}); // NOTE: deneme fontu

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const locale = await getLocale();

    return (
        <html lang={locale} suppressHydrationWarning>
            <body
                className={`${myFont.className} antialiased overflow-x-hidden`}
            >
                <ThemeProvider attribute={"class"} defaultTheme="system" enableSystem>
                    <NextIntlClientProvider>
                        <div className="flex min-h-screen">
                            <Sidebar />
                            <main className="flex-1 p-9 flex flex-col h-screen overflow-y-auto">
                                <Navbar />
                                {children}
                            </main>
                        </div>
                    </NextIntlClientProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
