
import "@/app/globals.css";

import { NextIntlClientProvider } from 'next-intl';
import { getLocale } from 'next-intl/server';
import { ThemeProvider } from 'next-themes';
import localFont from 'next/font/local';
import type { Metadata } from "next";
import Layout from '@/layout/Layout';
import { initZ3 } from "@/lib/init-z3";
import { Z3Provider } from "@/contexts/Z3Provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const myFont = localFont({
	src: '../../public/fonts/LufgaRegular.ttf'
});

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const locale = await getLocale();
	const init = await initZ3();

	return (
		<html lang={locale} suppressHydrationWarning>
			<body
				className={`${myFont.className} antialiased overflow-x-hidden`}
			>
				<Z3Provider z3={init}>
					<ThemeProvider attribute={"class"} defaultTheme="system" enableSystem>
						<NextIntlClientProvider>
							<Layout>
								{children}
							</Layout>
						</NextIntlClientProvider>
					</ThemeProvider>
				</Z3Provider>
			</body>
		</html>
	);
}
