import { NextIntlClientProvider } from 'next-intl';
import { Albert_Sans } from "next/font/google";
import { getLocale } from 'next-intl/server';
import { ThemeProvider } from 'next-themes';
import type { Metadata } from "next";
import "@/app/globals.css";

import Sidebar from '@/components/layout/Sidebar';

const albertSans = Albert_Sans({
	variable: "--font-albert-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const locale = await getLocale();

	return (
		<html lang={locale} suppressHydrationWarning>
			<body
				className={`${albertSans.variable} antialiased overflow-x-hidden`}
			>
				<ThemeProvider attribute={"class"} defaultTheme="system" enableSystem>
					<NextIntlClientProvider>
						<div className="flex min-h-screen">
							<Sidebar />
							<main className="flex-1 pt-6 pr-6 h-screen overflow-y-auto">
								<div className="w-full h-full px-px pt-px relative bg-gradient-to-br from-border via-popover to-border rounded-t-3xl overflow-hidden">
									<div className="p-6 bg-secondary h-full w-full rounded-[inherit]">
										{children}
									</div>
								</div>
							</main>
						</div>
					</NextIntlClientProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
